cd "C:\path\to\system\app"
RMDIR /S /Q "Books"
RMDIR /S /Q "Chrome"
RMDIR /S /Q "CloudPrint2"
RMDIR /S /Q "Drive"
RMDIR /S /Q "EditorsDocs"
RMDIR /S /Q "EditorsSheets"
RMDIR /S /Q "EditorsSlides"
RMDIR /S /Q "FitnessPrebuilt"
RMDIR /S /Q "GoogleEars"
RMDIR /S /Q "GoogleEarth"
RMDIR /S /Q "GoogleHindiIME"
RMDIR /S /Q "GoogleJapaneseInput"
RMDIR /S /Q "GooglePinyinIME"
RMDIR /S /Q "KoreanIME"
RMDIR /S /Q "Maps"
RMDIR /S /Q "Music2"
RMDIR /S /Q "Newsstand"
RMDIR /S /Q "Photos"
RMDIR /S /Q "PlayGames"
RMDIR /S /Q "PlusOne"
RMDIR /S /Q "PrebuiltKeep"
RMDIR /S /Q "PrebuiltGmail"
RMDIR /S /Q "PrebuiltNewsWeather"
RMDIR /S /Q "Street"
RMDIR /S /Q "Videos"
RMDIR /S /Q "YouTube"
cd "C:\path\to\system"
DEL /S /Q "recovery-from-boot.p"
exit